swagger: '2.0'
info:
  version: 6.0.2 (713b214)
  title: PostgREST API
  description: standard public schema
host: '0.0.0.0:3000'
basePath: /
schemes:
  - http
consumes:
  - application/json
  - application/vnd.pgrst.object+json
  - text/csv
produces:
  - application/json
  - application/vnd.pgrst.object+json
  - text/csv
paths:
  /:
    get:
      tags:
        - Introspection
      summary: OpenAPI description (this document)
      produces:
        - application/openapi+json
        - application/json
      responses:
        '200':
          description: OK
  /agent:
    get:
      tags:
        - agent
      parameters:
        - $ref: '#/parameters/rowFilter.agent.id'
        - $ref: '#/parameters/rowFilter.agent.fullname'
        - $ref: '#/parameters/rowFilter.agent.officeid'
        - $ref: '#/parameters/select'
        - $ref: '#/parameters/order'
        - $ref: '#/parameters/range'
        - $ref: '#/parameters/rangeUnit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/preferCount'
      responses:
        '200':
          schema:
            items:
              $ref: '#/definitions/agent'
            type: array
          description: OK
        '206':
          description: Partial Content
    post:
      tags:
        - agent
      parameters:
        - $ref: '#/parameters/body.agent'
        - $ref: '#/parameters/select'
        - $ref: '#/parameters/preferReturn'
      responses:
        '201':
          description: Created
    delete:
      tags:
        - agent
      parameters:
        - $ref: '#/parameters/rowFilter.agent.id'
        - $ref: '#/parameters/rowFilter.agent.fullname'
        - $ref: '#/parameters/rowFilter.agent.officeid'
        - $ref: '#/parameters/preferReturn'
      responses:
        '204':
          description: No Content
    patch:
      tags:
        - agent
      parameters:
        - $ref: '#/parameters/rowFilter.agent.id'
        - $ref: '#/parameters/rowFilter.agent.fullname'
        - $ref: '#/parameters/rowFilter.agent.officeid'
        - $ref: '#/parameters/body.agent'
        - $ref: '#/parameters/preferReturn'
      responses:
        '204':
          description: No Content
  /listing:
    get:
      tags:
        - listing
      parameters:
        - $ref: '#/parameters/rowFilter.listing.id'
        - $ref: '#/parameters/rowFilter.listing.addr'
        - $ref: '#/parameters/rowFilter.listing.price'
        - $ref: '#/parameters/rowFilter.listing.suburb'
        - $ref: '#/parameters/rowFilter.listing.agentid'
        - $ref: '#/parameters/select'
        - $ref: '#/parameters/order'
        - $ref: '#/parameters/range'
        - $ref: '#/parameters/rangeUnit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/preferCount'
      responses:
        '200':
          schema:
            items:
              $ref: '#/definitions/listing'
            type: array
          description: OK
        '206':
          description: Partial Content
    post:
      tags:
        - listing
      parameters:
        - $ref: '#/parameters/body.listing'
        - $ref: '#/parameters/select'
        - $ref: '#/parameters/preferReturn'
      responses:
        '201':
          description: Created
    delete:
      tags:
        - listing
      parameters:
        - $ref: '#/parameters/rowFilter.listing.id'
        - $ref: '#/parameters/rowFilter.listing.addr'
        - $ref: '#/parameters/rowFilter.listing.price'
        - $ref: '#/parameters/rowFilter.listing.suburb'
        - $ref: '#/parameters/rowFilter.listing.agentid'
        - $ref: '#/parameters/preferReturn'
      responses:
        '204':
          description: No Content
    patch:
      tags:
        - listing
      parameters:
        - $ref: '#/parameters/rowFilter.listing.id'
        - $ref: '#/parameters/rowFilter.listing.addr'
        - $ref: '#/parameters/rowFilter.listing.price'
        - $ref: '#/parameters/rowFilter.listing.suburb'
        - $ref: '#/parameters/rowFilter.listing.agentid'
        - $ref: '#/parameters/body.listing'
        - $ref: '#/parameters/preferReturn'
      responses:
        '204':
          description: No Content
  /office:
    get:
      tags:
        - office
      parameters:
        - $ref: '#/parameters/rowFilter.office.id'
        - $ref: '#/parameters/rowFilter.office.officename'
        - $ref: '#/parameters/select'
        - $ref: '#/parameters/order'
        - $ref: '#/parameters/range'
        - $ref: '#/parameters/rangeUnit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/preferCount'
      responses:
        '200':
          schema:
            items:
              $ref: '#/definitions/office'
            type: array
          description: OK
        '206':
          description: Partial Content
    post:
      tags:
        - office
      parameters:
        - $ref: '#/parameters/body.office'
        - $ref: '#/parameters/select'
        - $ref: '#/parameters/preferReturn'
      responses:
        '201':
          description: Created
    delete:
      tags:
        - office
      parameters:
        - $ref: '#/parameters/rowFilter.office.id'
        - $ref: '#/parameters/rowFilter.office.officename'
        - $ref: '#/parameters/preferReturn'
      responses:
        '204':
          description: No Content
    patch:
      tags:
        - office
      parameters:
        - $ref: '#/parameters/rowFilter.office.id'
        - $ref: '#/parameters/rowFilter.office.officename'
        - $ref: '#/parameters/body.office'
        - $ref: '#/parameters/preferReturn'
      responses:
        '204':
          description: No Content
definitions:
  agent:
    required:
      - id
      - fullname
      - officeid
    properties:
      id:
        format: integer
        type: integer
        description: |-
          Note:
          This is a Primary Key.<pk/>
      fullname:
        format: text
        type: string
      officeid:
        format: integer
        type: integer
        description: |-
          Note:
          This is a Foreign Key to `office.id`.<fk table='office' column='id'/>
    type: object
  listing:
    required:
      - id
      - addr
      - price
      - suburb
      - agentid
    properties:
      id:
        format: integer
        type: integer
        description: |-
          Note:
          This is a Primary Key.<pk/>
      addr:
        format: text
        type: string
      price:
        format: integer
        type: integer
      suburb:
        format: text
        type: string
      agentid:
        format: integer
        type: integer
        description: |-
          Note:
          This is a Foreign Key to `agent.id`.<fk table='agent' column='id'/>
    type: object
  office:
    required:
      - id
      - officename
    properties:
      id:
        format: integer
        type: integer
        description: |-
          Note:
          This is a Primary Key.<pk/>
      officename:
        format: text
        type: string
    type: object
parameters:
  preferParams:
    name: Prefer
    description: Preference
    required: false
    in: header
    type: string
    enum:
      - params=single-object
  preferReturn:
    name: Prefer
    description: Preference
    required: false
    in: header
    type: string
    enum:
      - return=representation
      - return=minimal
      - return=none
  preferCount:
    name: Prefer
    description: Preference
    required: false
    in: header
    type: string
    enum:
      - count=none
  select:
    name: select
    description: Filtering Columns
    required: false
    in: query
    type: string
  order:
    name: order
    description: Ordering
    required: false
    in: query
    type: string
  range:
    name: Range
    description: Limiting and Pagination
    required: false
    in: header
    type: string
  rangeUnit:
    name: Range-Unit
    description: Limiting and Pagination
    required: false
    default: items
    in: header
    type: string
  offset:
    name: offset
    description: Limiting and Pagination
    required: false
    in: query
    type: string
  limit:
    name: limit
    description: Limiting and Pagination
    required: false
    in: query
    type: string
  body.agent:
    name: agent
    description: agent
    required: false
    schema:
      $ref: '#/definitions/agent'
    in: body
  rowFilter.agent.id:
    name: id
    required: false
    format: integer
    in: query
    type: string
  rowFilter.agent.fullname:
    name: fullname
    required: false
    format: text
    in: query
    type: string
  rowFilter.agent.officeid:
    name: officeid
    required: false
    format: integer
    in: query
    type: string
  body.listing:
    name: listing
    description: listing
    required: false
    schema:
      $ref: '#/definitions/listing'
    in: body
  rowFilter.listing.id:
    name: id
    required: false
    format: integer
    in: query
    type: string
  rowFilter.listing.addr:
    name: addr
    required: false
    format: text
    in: query
    type: string
  rowFilter.listing.price:
    name: price
    required: false
    format: integer
    in: query
    type: string
  rowFilter.listing.suburb:
    name: suburb
    required: false
    format: text
    in: query
    type: string
  rowFilter.listing.agentid:
    name: agentid
    required: false
    format: integer
    in: query
    type: string
  body.office:
    name: office
    description: office
    required: false
    schema:
      $ref: '#/definitions/office'
    in: body
  rowFilter.office.id:
    name: id
    required: false
    format: integer
    in: query
    type: string
  rowFilter.office.officename:
    name: officename
    required: false
    format: text
    in: query
    type: string
externalDocs:
  url: 'https://postgrest.org/en/v6.0/api.html'
  description: PostgREST Documentation
